### ISSUE TITLE
GriefPrevention support 

### ISSUE THREAD

**Issue by JesusLion** [redstone/FreshWilderness#5] opened 2016-12-20 16:02 UTC
would be great!

**Comment by MarkehMe** [comment] 2016-12-20 22:56
Great idea :) will be in the next release

**Comment by Bysokar** [comment] 2017-04-11 01:30
@markehme Just grab the code from regenerator and tweak it for use with your plugin :)

Ps is this working finally? :D

**Comment by Bysokar** [comment] 2017-04-11 01:37
Scratch that ill add the support and offer it to You As a Pr. Good work on this plugin dude!

**Comment by MarkehMe** [comment] 2017-04-11 01:59
@Bysokar that would be awesome, thanks :)

**Comment by ArtNRG** [comment] 2017-06-22 11:06
@MarkehMe the issue is already opened, will be glad to see this support.

**Comment by Bysokar** [comment] 2017-06-22 11:35
Haha Regenerator not for you hey bud

**Comment by MarkehMe** [comment] 2017-09-02 04:50
✅ GriefPrevention support added

**Closed** 2017-09-02 04:50 UTC
Labels: enhancement
